import type { Metadata } from "next";
import { Montserrat, Raleway } from "next/font/google";
import "./globals.css";
import NavDelay from "@/components/NavDelay";
import { TimerProvider } from "@/context/TimerContext";

export const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-montserrat",
});

export const raleway = Raleway({
  subsets: ["latin"],
  weight: ["700"],
  display: "swap",
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable} ${raleway.variable}`}>
      <body>
        <TimerProvider>
          <nav className="nav py-2">
            <div className="wrapper flex justify-center items-center">
              <NavDelay />
            </div>
          </nav>
          {children}
        </TimerProvider>
      </body>
    </html>
  );
}
